title: XMDG Czech
author: David Malý
email: info@xmdg.cz
description: >
  Oficiální stránky Xamarin Developers Group Czech komunity



sass:
    style: compressed
markdown: kramdown


kramdown:
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1