name: Xamarin Developers Group Czech Blog
title: XMDGCZ
url: http:/xmdg.cz
author: David Malý
email: info@xmdg.cz
description: >
  Oficiální stránky Xamarin Developers Group Czech komunity
permalink: /:year/:month/:day/:title/

sass:
    style: compressed

markdown: kramdown

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'LICENSE.txt', '.idea']

kramdown:
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

meetup:
  group: "xmdg-cz"
  events:
    event_id: "" #Meetup event ID
t:
  en:
    months:
      january: "Jan"
      february: "Feb"
      march: "Mar"
      april: "Apr"
      may: "May"
      june: "Jun"
      july: "Jul"
      august: "Aug"
      september: "Sep"
      october: "Oct"
      november: "Nov"
      december : "Dec"
  cs:
    months:
      january: "ledna"
      february: "února"
      march: "března"
      april: "dubna"
      may: "května"
      june: "června"
      july: "července"
      august: "srpna"
      september: "září"
      october: "října"
      november: "listopadu"
      december : "prosince"

collections:
  authors:
    output: true
    permalink: /:name
  custom-categories:
    output: true
    permalink: /:name
  custom-categories-courses:
    output: true
    permalink: /:name

defaults:
  - scope:
      type: "posts"
    values:
      lang: "cs"
      menuHighlight: "Blog" # which item should be highlighted in navigation bar
      excerpt_separator: <!--excerpt-->
  - scope:
      type: "posts"
      path: "_posts/*/courses/*"
    values:
      lang: "cs"
      menuHighlight: "Kurzy" # which item should be highlighted in navigation bar
      excerpt_separator: <!--excerpt-->
  - scope:
      type: "pages"
    values:
      lang: "cs"
  - scope:
      path: ""
      type: "authors"
    values:
      type: "posts"
      layout: author
      excerpt_separator: <!--excerpt-->
  - scope:
      path: ""
      type: "custom-categories"
    values:
      layout: blog-list-posts
      menuHighlight: "Blog" # which item should be highlighted in navigation bar
  - scope:
      path: ""
      type: "custom-categories-courses"
    values:
      layout: courses-list-posts
      menuHighlight: "Kurzy" # which item should be highlighted in navigation bar
      excerpt_separator: <!--excerpt-->


